### PR TITLE
Add TrendMicro deepsec log forwarding syslog support

### PR DESCRIPTION
**Pull request by justjais**
Add TrendMicro deepsec log forwarding syslog support, ref: https://github.com/ansible-collections/trendmicro.deepsec/pull/2, I am expecting this PR to get merged max by tomorrow and once that's merged this added support should also start working as expected.

cc. @liquidat

### CODE REVIEW

**Comment by liquidat** [comment]
@justjais Looks good! Short question though: it all depends on the module `syslog_config`, where does this come from? I guess from the corresponding trendmicro collection? If so, we should add a short line to the documentation what the collection name is that needs to be present so that this works.

**Comment by justjais** [comment]
@liquidat thanks and yea make sense, I've added the required info under role requirement section.

**Comment by liquidat** [comment]
Thanks for adding this. Looks good from my side, without having tested it though.

**Comment by justjais** [comment]
@liquidat thanks for the update and yes having it not tested is a risk

**Pull request merged**
